server:
  port: 8080

naver:
  map:
    client-id: ${NAVER_CLIENT_ID}

spring:
  profiles:
    active: local

  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
  # Redis 서버 (듀오 매칭 시스템에 필요)
  data:
    redis:
      host: redis-14469.c340.ap-northeast-2-1.ec2.redns.redis-cloud.com
      port: 14469
      password: ${REDIS_PASSWORD}
      timeout: 2s

  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

# park
ai:
  api:
    base-url: https://kdt-api-function.azurewebsites.net
    key: "${ALAN_KEY}"

cloud:
  aws:
    access-key: "${AWS_ACCESS_KEY}"
    secret-key: "${AWS_SECRET_KEY}"
    region: ap-northeast-2
    s3:
      bucket-name: "${BUCKET_NAME}"
